site_name: gd.docs
site_author: nekitdev
site_description: Documentation for Geometry Dash.

repo_name: gd-programming/gd.docs
repo_url: https://github.com/gd-programming/gd.docs

remote_branch: github-pages

watch:
  - docs

nav:
  - "Index": "index.md"
  - "Credits": "credits.md"

  - "Endpoints":
    - "Comments":
      - "Delete Account Comment": "endpoints/comments/delete_account_comment.md"
      - "Delete Level Comment": "endpoints/comments/delete_level_comment.md"
    - "Friend Requests":
      - "Accept Friend Request": "endpoints/friend_requests/accept_friend_request.md"
      - "Delete Friend Request": "endpoints/friend_requests/delete_friend_request.md"
    - "Levels":
      - "Delete Level": "endpoints/levels/delete_level.md"
      - "Download Level": "endpoints/levels/download_level.md"
    - "Messages":
      - "Delete Message": "endpoints/messages/delete_message.md"
      - "Read Message": "endpoints/messages/read_message.md"
    - "Users":
      - "Block User": "endpoints/users/block_user.md"

  - "Resources":
    - "Server":
      - "Secrets": "resources/server/secrets.md"
      - "Versions": "resources/server/versions.md"

  - "Topics":
    - "Encoding":
      - "Base64": "topics/encoding/base64.md"
      - "Checks": "topics/encoding/checks.md"
      - "Random String, UUID and UDID": "topics/encoding/ids.md"
      - "Seeds": "topics/encoding/seeds.md"
      - "XOR": "topics/encoding/xor.md"

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: deep orange
      accent: light blue

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
